/**
 * @fileoverview gRPC-Web generated client stub for rkapi.auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: auth.proto

/* eslint-disable */
// @ts-nocheck


goog.provide('proto.rkapi.auth.AuthClient');
goog.provide('proto.rkapi.auth.AuthPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.google.protobuf.Empty');
goog.require('proto.rkapi.auth.CreateUserRequest');
goog.require('proto.rkapi.auth.LoginRequest');
goog.require('proto.rkapi.auth.LoginResponse');
goog.require('proto.rkapi.auth.UpdatePasswordRequest');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rkapi.auth.AuthClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rkapi.auth.AuthPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.auth.LoginRequest,
 *   !proto.rkapi.auth.LoginResponse>}
 */
const methodDescriptor_Auth_Login = new grpc.web.MethodDescriptor(
  '/rkapi.auth.Auth/Login',
  grpc.web.MethodType.UNARY,
  proto.rkapi.auth.LoginRequest,
  proto.rkapi.auth.LoginResponse,
  /**
   * @param {!proto.rkapi.auth.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rkapi.auth.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.rkapi.auth.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rkapi.auth.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rkapi.auth.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.auth.AuthClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.auth.Auth/Login',
      request,
      metadata || {},
      methodDescriptor_Auth_Login,
      callback);
};


/**
 * @param {!proto.rkapi.auth.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rkapi.auth.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.rkapi.auth.AuthPromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.auth.Auth/Login',
      request,
      metadata || {},
      methodDescriptor_Auth_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.auth.CreateUserRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Auth_CreateUser = new grpc.web.MethodDescriptor(
  '/rkapi.auth.Auth/CreateUser',
  grpc.web.MethodType.UNARY,
  proto.rkapi.auth.CreateUserRequest,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.auth.CreateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.auth.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.auth.AuthClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.auth.Auth/CreateUser',
      request,
      metadata || {},
      methodDescriptor_Auth_CreateUser,
      callback);
};


/**
 * @param {!proto.rkapi.auth.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.auth.AuthPromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.auth.Auth/CreateUser',
      request,
      metadata || {},
      methodDescriptor_Auth_CreateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.auth.UpdatePasswordRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Auth_UpdatePassword = new grpc.web.MethodDescriptor(
  '/rkapi.auth.Auth/UpdatePassword',
  grpc.web.MethodType.UNARY,
  proto.rkapi.auth.UpdatePasswordRequest,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.auth.UpdatePasswordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.auth.UpdatePasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.auth.AuthClient.prototype.updatePassword =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.auth.Auth/UpdatePassword',
      request,
      metadata || {},
      methodDescriptor_Auth_UpdatePassword,
      callback);
};


/**
 * @param {!proto.rkapi.auth.UpdatePasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.auth.AuthPromiseClient.prototype.updatePassword =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.auth.Auth/UpdatePassword',
      request,
      metadata || {},
      methodDescriptor_Auth_UpdatePassword);
};


}); // goog.scope

