/**
 * @fileoverview gRPC-Web generated client stub for rkapi.jobs
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: jobs.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.rkapi.jobs.JobsClient');
goog.provide('proto.rkapi.jobs.JobsPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.google.protobuf.Empty');
goog.require('proto.rkapi.auth.Authorization');
goog.require('proto.rkapi.jobs.Job');
goog.require('proto.rkapi.jobs.JobId');
goog.require('proto.rkapi.jobs.JobUpdateRequest');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rkapi.jobs.JobsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.rkapi.jobs.JobsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.auth.Authorization,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Jobs_Post = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Post',
  grpc.web.MethodType.UNARY,
  proto.rkapi.auth.Authorization,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.auth.Authorization} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.auth.Authorization} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.post =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Post',
      request,
      metadata || {},
      methodDescriptor_Jobs_Post,
      callback);
};


/**
 * @param {!proto.rkapi.auth.Authorization} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.post =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Post',
      request,
      metadata || {},
      methodDescriptor_Jobs_Post);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.jobs.JobUpdateRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Jobs_Claim = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Claim',
  grpc.web.MethodType.UNARY,
  proto.rkapi.jobs.JobUpdateRequest,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.jobs.JobUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.claim =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Claim',
      request,
      metadata || {},
      methodDescriptor_Jobs_Claim,
      callback);
};


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.claim =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Claim',
      request,
      metadata || {},
      methodDescriptor_Jobs_Claim);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.jobs.JobUpdateRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Jobs_Unclaim = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Unclaim',
  grpc.web.MethodType.UNARY,
  proto.rkapi.jobs.JobUpdateRequest,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.jobs.JobUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.unclaim =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Unclaim',
      request,
      metadata || {},
      methodDescriptor_Jobs_Unclaim,
      callback);
};


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.unclaim =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Unclaim',
      request,
      metadata || {},
      methodDescriptor_Jobs_Unclaim);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.jobs.JobUpdateRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Jobs_Pickup = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Pickup',
  grpc.web.MethodType.UNARY,
  proto.rkapi.jobs.JobUpdateRequest,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.jobs.JobUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.pickup =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Pickup',
      request,
      metadata || {},
      methodDescriptor_Jobs_Pickup,
      callback);
};


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.pickup =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Pickup',
      request,
      metadata || {},
      methodDescriptor_Jobs_Pickup);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.jobs.JobUpdateRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Jobs_Dropoff = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Dropoff',
  grpc.web.MethodType.UNARY,
  proto.rkapi.jobs.JobUpdateRequest,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.jobs.JobUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.dropoff =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Dropoff',
      request,
      metadata || {},
      methodDescriptor_Jobs_Dropoff,
      callback);
};


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.dropoff =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Dropoff',
      request,
      metadata || {},
      methodDescriptor_Jobs_Dropoff);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.jobs.JobUpdateRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Jobs_Cancel = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Cancel',
  grpc.web.MethodType.UNARY,
  proto.rkapi.jobs.JobUpdateRequest,
  proto.google.protobuf.Empty,
  /**
   * @param {!proto.rkapi.jobs.JobUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.protobuf.Empty.deserializeBinary
);


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.cancel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Cancel',
      request,
      metadata || {},
      methodDescriptor_Jobs_Cancel,
      callback);
};


/**
 * @param {!proto.rkapi.jobs.JobUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.cancel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Cancel',
      request,
      metadata || {},
      methodDescriptor_Jobs_Cancel);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.rkapi.jobs.Job>}
 */
const methodDescriptor_Jobs_Jobs = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Jobs',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.google.protobuf.Empty,
  proto.rkapi.jobs.Job,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rkapi.jobs.Job.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rkapi.jobs.Job>}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.jobs =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rkapi.jobs.Jobs/Jobs',
      request,
      metadata || {},
      methodDescriptor_Jobs_Jobs);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.rkapi.jobs.Job>}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.jobs =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/rkapi.jobs.Jobs/Jobs',
      request,
      metadata || {},
      methodDescriptor_Jobs_Jobs);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rkapi.jobs.JobId,
 *   !proto.rkapi.jobs.Job>}
 */
const methodDescriptor_Jobs_Get = new grpc.web.MethodDescriptor(
  '/rkapi.jobs.Jobs/Get',
  grpc.web.MethodType.UNARY,
  proto.rkapi.jobs.JobId,
  proto.rkapi.jobs.Job,
  /**
   * @param {!proto.rkapi.jobs.JobId} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.rkapi.jobs.Job.deserializeBinary
);


/**
 * @param {!proto.rkapi.jobs.JobId} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rkapi.jobs.Job)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rkapi.jobs.Job>|undefined}
 *     The XHR Node Readable Stream
 */
proto.rkapi.jobs.JobsClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Get',
      request,
      metadata || {},
      methodDescriptor_Jobs_Get,
      callback);
};


/**
 * @param {!proto.rkapi.jobs.JobId} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rkapi.jobs.Job>}
 *     Promise that resolves to the response
 */
proto.rkapi.jobs.JobsPromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/rkapi.jobs.Jobs/Get',
      request,
      metadata || {},
      methodDescriptor_Jobs_Get);
};


}); // goog.scope

