name: Build Android App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit hash
        id: get-hash
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"
      
      - name: Cache Rust files
        uses: actions/cache@v4
        with:
          path: |
            src-tauri/target/
            ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('src-tauri/Cargo.lock') }}-${{ steps.get-hash.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ hashFiles('src-tauri/Cargo.lock') }}-
            ${{ runner.os }}-rust-
          save-always: true
      
      - name: Give tar root permissions
        run: |
          sudo chown root /bin/tar
          sudo chmod u+s /bin/tar

      - name: Restore NDK and SDK cache
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk/ndk/
            /usr/local/lib/android/sdk/platform-tools/
            /usr/local/lib/android/sdk/emulator/
            /usr/local/lib/android/sdk/tools/
          key: ${{ runner.os }}-android-ndk-sdk-${{ steps.get-hash.outputs.hash }}
          restore-keys: ${{ runner.os }}-android-ndk-sdk-
          save-always: true

      - name: Get cache results
        id: cache
        run: |
          echo "::set-output name=ndk::$([[ "$(ls -l /usr/local/lib/android/sdk/ndk | head -n 1 | cut -d' ' -f1)" == "total" ]] && echo true || echo false))"
          echo "::set-output name=sdk::$([[ "$(ls -l /usr/local/lib/android/sdk/platform-tools | head -n 1 | cut -d' ' -f1)" == "total" ]] && echo true || echo false))"
          echo "::set-output name=rust::$([[ "$(ls -l src-tauri/target | head -n 1 | cut -d' ' -f1)" == "total" ]] && echo true || echo false))"
      
      - name: Configure Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        if: steps.cache.outputs.rust == 'false'
        with:
          toolchain: stable
          targets: aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        if: steps.cache.outputs.sdk == 'false'

      - name: Setup Android NDK
        run: sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.11718014"
        if: steps.cache.outputs.ndk == 'false'

      - name: Keystore Config
        run: |
          mkdir -p ~/.android/keystore/

          echo "${{ secrets.KEYSTORECFG_B64 }}" >> src-tauri/gen/android/key.properties.b64
          echo "${{ secrets.KEYSTORE_B64 }}" >> ~/.android/keystore/keystore-prod.jks.b64
          
          base64 -d src-tauri/gen/android/key.properties.b64 >> src-tauri/gen/android/key.properties
          base64 -d ~/.android/keystore/keystore-prod.jks.b64 >> ~/.android/keystore/keystore-prod.jks

          sed -i "s/onlycs/runner/g" src-tauri/gen/android/key.properties

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Install Tauri CLI
        run: cargo install tauri-cli@^2.0.0-beta
        if: steps.cache.outputs.rust == 'false'
      
      - name: Build Android App
        run: cargo tauri android build --apk
        env:
          NDK_HOME: /usr/local/lib/android/sdk/ndk/27.0.11718014

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-universal-release-unsigned.apk
          path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
