name: Build Android App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore build cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: "src-tauri -> target"
      
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r26d'
          link-to-sdk: true
          local-cache: true

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build app with Tauri CLI
        run: bunx @tauri-apps/cli@next android build --apk
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-universal-release-unsigned.apk
          path: src-tauri/gen/android/app/build/outputs/apk/release/app-universal-release-unsigned.apk