name: Deploy to Google Artifact Registry
on:
  push:
    tags:
      - '*'
  workflow_dispatch:


jobs:
  docker-release:
    name: Release Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: "src-grpc -> src-grpc/target"

      - name: Setup .env
        run: echo 'DATABASE_URL = "${{ secrets.DATABASE_URL }}"' > src-grpc/.env

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build release
        run: |
          cd src-grpc
          cargo build --release

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push Docker Image
        id: docker-push-tagged
        uses: docker/build-push-action@v2
        with:
          context: src-grpc
          file: src-grpc/Dockerfile
          push: true
          tags: |
            us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/grpc-server:${{ steps.get-tag.outputs.short_ref }}
            us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/grpc-server:latest
